theme: jekyll-theme-architect
title: Resources
description: A collection of documents to help you understand how to run an innovation workshop
collections_dir: documents
collections:
  ideas_lab:
    output: true
  sandpit:
    output: true
  guides:
    output: true
  poster_session:
    output: true


 
