theme: jekyll-theme-architect
title: Resources
description: A collection of documents to help you understand how to run and Ideas Lab
collections_dir: documents
collections:
  ideas_lab:
    output: true
  sandpit:
    output: true


 
